import type { Metadata } from 'next';

import { ThemeProvider } from '@mui/material/styles';

import './globals.css';
import { roboto, theme } from './theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
